### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by Evizero** [JuliaStats/MLBase.jl#22]
Could someone go ahead and tag a new version? travis keeps failing on me on 0.4 because I have this package in require. As far as I can test locally, it seems that the issue is already fixed in master

**Comment by Evizero** [comment]
pretty please? the README badges even show that the 0.4 error should go away with a new tagged version

**Comment by Evizero** [comment]
Does no one currently have the time to maintain this package? or is the responsible person on holiday? 

In the odd case that no one is interested in maintaining this anymore, could I at least help maybe? I'd hate to see such a cool package go to waste.

**Comment by lindahua** [comment]
I am making a new tag here: https://github.com/JuliaLang/METADATA.jl/pull/3288

**Comment by lindahua** [comment]
All these packages are maintained by volunteers, and sometimes the response may not be as fast as you expect.

**Comment by lindahua** [comment]
Tagged: https://github.com/JuliaLang/METADATA.jl/pull/3288

**Comment by Evizero** [comment]
Thank you!

I know, and I appreciate all the efforts. I really don't enjoy being this annoying all the time. I'm just trying to make progress on my packages
