### ISSUE TITLE
Failing to load MLBase in Julia v0.4

### ISSUE THREAD

**Issue by silenj** [JuliaStats/MLBase.jl#24]
I need to have a working NMF package which depends on MLBase which fails on loading in a manner I do not understand. On line 217 in MLBase/src/perfeval.jl there is type assertion together with a tuple in the argument list which does not work in Julia v0.4 but works in the v0.3. Why is this so? If the "preds::(PV,SV)" is changed to "preds" the error is moved elsewhere indicating it is the "type tuple" which is the problem. Why? How should this be fixed? One cannot remove them all as there are other functions dependent on them.

Regards Johan

**Comment by lindahua** [comment]
Fixed and working in latest version.
