### ISSUE TITLE
Issues with Julia v0.5

### ISSUE THREAD

**Issue by pevnak** [JuliaStats/MLBase.jl#30]
Hi all,
I have found that I need to comment 
using ArrayViews in MLBase.jl due to clash with Julia's own function in v0.5.

Tomas

**Comment by ararslan** [comment]
Hi Tomas,

Thanks for the heads up. This package seems to have slipped under the radar. Indeed, the package tests don't pass at all on Julia 0.5. Only one registered package appears to have a current version that depends on it, so I wonder if we might be better off in the long run deprecating this in favor of something from the [JuliaML](https://github.com/JuliaML) organization. (cc @johnmyleswhite on that) In the interim though I can take a look here to see if I can get it cleaned up for 0.5.

**Comment by pevnak** [comment]
Hi Alex,
I was looking into Julia ML but I have not find any package that would implement calculation of prcurve and roc curve, which are sometimes helpful. Have I missed something?
If not, then I think that MLBase still have its place.

**Comment by ararslan** [comment]
Oh, I guess I didn't realize JuliaML didn't reimplement this stuff. I wonder if perhaps this should be merged into StatsBase? (cc @andreasnoack @nalimilan) Or maybe we should just leave everything as-is. ¯\\\_(ツ)\_/¯
