### ISSUE TITLE
Port to 0.7/1.0

### ISSUE THREAD

**Issue by lsindoni** [JuliaStats/MLBase.jl#44]
An update might be in order. Tests are passing for 0.7, but the package fails to precompile in 1.0.

**Comment by lsindoni** [comment]
I'm working on this, but a requirement is to have IterTools ready for the upgrade.

**Comment by ararslan** [comment]
I believe @iamed2 has IterTools (mostly?) working on Julia 0.7/1.0.

**Comment by iamed2** [comment]
IterTools works on 0.7 and 1.0

**Comment by lsindoni** [comment]
Ok, I'll do the final checks and prepare the PR.
