### ISSUE TITLE
Control randomness of Kfold

### ISSUE THREAD

**Issue by ngiann** [JuliaStats/MLBase.jl#56]
Amonst other reasons, it would be useful for the sake of reproducibility if we could control the randomness in `Kfold`'s behaviour. For instance:

```
Kfold(10,2) # call first time
Kfold([10, 2, 7, 5, 8, 1, 9, 6, 4, 3], 2, 5.0)

Kfold(10,2) # when called again
Kfold([2, 6, 10, 8, 5, 7, 3, 1, 4, 9], 2, 5.0)
```

Perhaps something along the lines of `Kfold(10,2; seed = 123)` would be nice?

Or perhaps there are reasons that speak against controlling the randomness?

Many thanks for this wonderful package.

**Comment by AsafManela** [comment]
Yep. The right way to do it is to add an optional rng::RandomNumberGenerator argument to Kfold.
Most of julia moved away from the global rng to this way of doing things. 
PRs welcome!
